name: Changelog validator
on:
  # Require a changelog for any PR going to main.
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'doc/**'
      - README.md

jobs:
  call-workflow-changelog-validate:
    uses: project-llzk/open-source-release-helpers/.github/workflows/changelog-validator.yml@main
    secrets: inherit
