name: Create release candidate

on:
  workflow_dispatch:

jobs:
  call-workflow-create-release-candidate:
    uses: project-llzk/open-source-release-helpers/.github/workflows/create-release-candidate.yml@main
    secrets: inherit

