name: Create Release PR

on:
  workflow_dispatch:

jobs:
  call-workflow-create-release-pr:
    uses: project-llzk/open-source-release-helpers/.github/workflows/create-release-pr.yml@main
    secrets: inherit
