name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  call-workflow-release:
    uses: project-llzk/open-source-release-helpers/.github/workflows/release.yml@main
    secrets: inherit
  call-deploy-github-pages:
    needs: call-workflow-release
    uses: ./.github/workflows/deploy-github-pages.yml
    secrets: inherit
    with:
      version: '${{ needs.call-workflow-release.outputs.version }}'
